### Site Settings ###
title               : taruma.online
description         : >-                               # >- means to ignore newlines until "url:"
                      Music Composer/Producer, (Python) Programmer, Blogger, Philomath/Lifelong Learning

url                 : "https://taruma.online"          # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                               # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : taruma/taruma.github.io          # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
remote_theme        : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Taruma Sakti Megariansyah
  image             : assets/images/my-profpic-2019.jpg
# behance           : your_username
# dribbble          : your_username
  email             : hi@taruma.info
  # facebook          : your_username
  github            : taruma
# gitlab            : your_username
  instagram         : tarumainfo
  linkedin          : taruma
  medium            : taruma
  soundcloud        : taruma-sakti
  spotify           : 12141012102
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : tarumainfo
# vimeo             : your_username
  youtube           : tarumainfo


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock